language: php
php:
  - 7.4
before_install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --prefer-stable --no-suggest
script:
  - vendor/bin/phpunit
